# Substitute with the crawler's service name
crawler_name:
    # Substitue with the crawl to launch's name
    main:
        # Uncomment needed fields and replace with needed value
        access_token: 'access_token'
        # refresh_token: 'refresh_token'
        # token_secret: 'token_secret'
        # consumer_key: 'consumer_key'
        # expires: 'expires'
