language: python
python:
- '2.7'
install:
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install tox>=2.1.1 coveralls
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . )
after_success: coveralls --verbose
notifications:
  slack:
    secure: i+OodR6DhPNnqNpTo6f1WjxMQfdklSJcAgUdUjmZxQu6DSpO2MpQj7xOvQKCURlJdcWjuI+6i9epNIikKE6ow/jDX4+Js/uMyRpcxiK4ot8cO1TvmJvlHHsc6wwRJgYBzJJ9AgiBnfl7ITYSrDqi4fWG4+m8Z+zxlgQ5vnIit6yr16qPgmYQE3ztjpakeThAuPqnjTWbaXc3uttsOhAWubovrkeH3V+9gymHxr8WfjGeXJoaNKOz9T+mdQw0ikA+Ytomb3dbN4GGghorjl5V06n/FVcJrduYN1kpohh7veiMbAAYhyZqKmORnPuVvofmQuVqJhhLZz5r/9MGHyVlnzbKDs+jX/Rc2DL1j3p9GsvIjW185LEGY2Rk5kNWZa78NVEXmLrk2KhlLWpqSnwKoYiPOM0B99r9NbuqLf1YFl4vmR0aQvNtpDWyLqhVqvm8As4u8SjAEDXcLh5DUd2vBfbA+E6mJAdpzCOgxSr5zl2wEqC9LEdhZib9GMJnL0NzNSoSYTskUUJoUr6SYM7IU6htMmgEVUy8iFOdCPs80DPbBxhP4qMXfFRwBS1qb2r8BMqbKOp1yO41HM9+Dhwohyt1bxwoqXjFiaaJnRFpQqLVwK0iYR90S54U+54GZ3i6EIdPCHcadFPOvS4AMso0VgorI7Ipt1KQEhEPVnHkz88=
