elasticsearch: &elasticsearch localhost:13000

elasticsearch:
    ES_CARD_TYPE: item
    ES_HOST: *elasticsearch
    ES_INDEX: docido

    ES_STORE_HOST: *elasticsearch
    ES_STORE_INDEX: store_docido
    ES_STORE_TYPE: cached_item

    MAPPING:
        # describe Elasticsearch "docido" index mapping
        docido:
            id:
                type: string
                index: not_analyzed
            title:
                type: string
            description:
                type: string
            date:
                type: date
                format: "E MMM d H:m:s Z y||d MMM 'at' H:m||y-M-d'T'H:m:s'Z'||y-M-d'T'H:m:s||y-M-d'T'H:m:s.S||y-M-d'T'H:m:s.SS||yyyy-MM-dd'T'HH:mm:ssZ"
                locale: en_US.UTF-8
            kind:
                type: string
                index: not_analyzed
            author.name:
                properties:
                    author:
                        type: nested
                        properties:
                            name:
                                type: string
                                index: not_analyzed
            attachments.title:
                properties:
                    attachments:
                        type: nested
                        properties:
                            title:
                                type: string
            attachments.origin_id:
                properties:
                    attachments:
                        type: nested
                        properties:
                            origin_id:
                                type: string
                                index: not_analyzed
            attachments.type:
                properties:
                    attachments:
                        type: nested
                        properties:
                            type:
                                type: string
            attachments.type:
                properties:
                    attachments:
                        type: nested
                        properties:
                            description:
                                type: string

pull_crawlers:
    indexing:
      pipeline:
        - CheckProcessor
        # - ElasticsearchMapping
        - Elasticsearch
        - LocalKV

      check_processor:
        schemas:
          card:
              kind:
                contact:
                    options:
                        extra: true
                        required: true
                    content:
                        id: basestring
                        name: basestring
                        username: basestring
                        kind: basestring

              default:
                options:
                    extra: true
                    required: true
                content:
                    id: basestring
                    title: basestring
                    description: basestring
                    date:
                        All:
                            - int
                            - Range:
                                min: 0
                    kind: basestring
                    author:
                        nested:
                            name: basestring
                    attachments:
                        -
                            # title: basestring
                            # origin_id: basestring
                            type: basestring
                            # description: basestring

          query:
            # describes schema of queries made by your crawler
            content:
              query: object

    crawlers:
        # This is the section dedicated to Python pull-crawlers
        # You can ship as many crawler as you want in one single Python
        # module.
        @NAME@:
            indexing:
                # This section allows you to describe additional fields,
                # that must be specified in items pushed by your crawler.
                # This is help you test your crawler more efficiently.
                check_processor:
                    schemas:
                        card:
                            default:
                                gen: long
                            kind:
                                contact:
                                    gen: long

            mapping:
                gen:
                    type: long
