pull_crawlers:
    crawlers:
        # This is the section dedicated to Python pull-crawlers
        # You can ship as many crawler as you want in one single Python
        # module.
        trello:
            indexing:
                # This section allows you to describe additional fields,
                # that must be specified in items pushed by your crawler.
                # This is help you test your crawler more efficiently.
                check_processor:
                    schemas:
                        card:
                            default:
                                gen: long
    indexing:
        pipeline:
        # The 'pipeline' section specifies the processors used to process
        # items pushed by your crawlers.
        # The default settings:
        # 1. checks schema of pushed items
        # 2. stores pushed items in Elasticsearch and
        #    the key-value store locally
            - CheckProcessor
            - ElasticsearchMapping
            - Elasticsearch
            - LocalKV
            - LocalDumbIndex

        # Framework enforces content of items pushed by your crawler
        # forewarn you errors that might occurs downstream.
        # The 'check_processor' section below describes the list of mandatory
        # fields expected by the framework.
        check_processor:
            schemas:
                # describes schema of items pushed by your crawler
                card:
                    kind:
                        # describes alternate schema for items based on their kinds
                        # below is an example for a 'contact' kind
                        contact:
                            options:
                                extra: true
                                required: true
                            content:
                                id: unicode
                                name: unicode
                                username: unicode
                                kind: unicode

                    default:
                        # describes default schema for items
                        options:
                            # all fields specified in the 'content' section
                            # are mandatory
                            extra: true
                            # additional fields are allowed
                            required: true
                        content:
                            # this section describes the mandatory schema.
                            # Syntax is `yamlious` compliant.
                            # See https://github.com/cogniteev/yamlious
                            # for syntax documentation
                            id: unicode
                            title: unicode
                            description: unicode
                            date:
                                All:
                                    - int
                                    - Range:
                                        min: 0
                            kind: unicode
                            author:
                                nested:
                                    name: unicode
                            attachments:
                                -
                                    type: unicode

                query:
                    content:
                        query: object
